# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'media/graph.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.max_s = QtWidgets.QLabel(Form)
        self.max_s.setObjectName("max_s")
        self.horizontalLayout.addWidget(self.max_s)
        self.avrg = QtWidgets.QLabel(Form)
        self.avrg.setObjectName("avrg")
        self.horizontalLayout.addWidget(self.avrg)
        self.min_s = QtWidgets.QLabel(Form)
        self.min_s.setObjectName("min_s")
        self.horizontalLayout.addWidget(self.min_s)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.graphicsView = PlotWidget(Form)
        self.graphicsView.setMaximumSize(QtCore.QSize(16777215, 200))
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.max_s.setText(_translate("Form", "<html><head/><body><p>максимальная</p><p> длинна:</p></body></html>"))
        self.avrg.setText(_translate("Form", "<html><head/><body><p>средняя</p><p> длинна:</p></body></html>"))
        self.min_s.setText(_translate("Form", "<html><head/><body><p>минимальная</p><p> длинна:</p></body></html>"))


from pyqtgraph import PlotWidget
